### ISSUE TITLE
TypeError: 'int' object is not iterable with application/json data

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1415] opened 2016-04-28 13:10 UTC
Originally reported by: **Evgeny Petrov (Bitbucket: [master_groosha](http://bitbucket.org/master_groosha), GitHub: Unknown)**

----------------------------------------

I'm getting this error when recieving `application/json` data with CherryPy:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/lib/encoding.py", line 260, in __call__
    ct.params['charset'] = self.find_acceptable_charset()
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/lib/encoding.py", line 169, in find_acceptable_charset
    if encoder(self.default_encoding):
  File "/usr/local/lib/python3.4/dist-packages/cherrypy/lib/encoding.py", line 110, in encode_string
    for chunk in self.body:
TypeError: 'int' object is not iterable
```

And my simpliest code is:
```python
import cherrypy

class WebhookServer(object):
    @cherrypy.expose
    def index(self): 
        print(cherrypy.request.headers)
        return 200

cherrypy.config.update({
    'server.socket_host': "127.0.0.1",
    'server.socket_port': 5657,
})
cherrypy.quickstart(WebhookServer(), '/', {'/': {}})
```
`print()` function isn't the problem: if I leave `return` the problem still here. I was using CherryPy 4.0.0, then updated to 5.0.3 and the problem is still here.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1415

**Comment by webknjaz** [comment] 2016-07-22 12:31
I believe this doesn't have anything to do with `application/json`.
Topic starter returns `int` and it gets iterated thus raising exception, according to traceback provided. He doesn't even use `cherrypy.tools.json_in/out` to handle json. It seems he didn't know how to set a status code.

Regarding the issue, there are two options:
1) It's not a bug (handler is expected to return string-like object)
2) Code, which processes handler output should try converting it into appropriate type 

@jaraco I think this could be closed in case (1)

**Comment by jaraco** [comment] 2016-07-22 14:17
Agreed. Just replace `return 200` with `return` and the code will run fine.

**Closed by jaraco** 2016-07-22 14:17 UTC
Labels: bug, engine, major

**Comment by souravBhandari** [comment] 2020-04-18 16:02
a

**Comment by souravBhandari** [comment] 2020-04-18 16:04
self.view_records()
#-------------- Database connection -------------------
    def run_query(self,stmt,para=()):
        con=MySQLdb.connect("localhost","root","",port=3325)
        con.select_db("StudentList")
        cur=con.cursor()
        query_res=cur.execute(stmt,para)
        con.commit()
        return query_res

    def view_records(self):
        records=self.tree.get_children()    
        for element in records:
            self.tree.delete(element)
        stmt="select * from Student"
        db_table=self.run_query (stmt)
        for data in db_table:
            self.tree.insert('',10,text=data[0],values=data[1])


error showing me is :
   for data in db_table:
TypeError: 'int' object is not iterable
