### ISSUE TITLE
Read The Docs has several dead links

### ISSUE THREAD

**Issue by 1kastner** [cherrypy/cherrypy#1587] opened 2017-04-04 16:55 UTC
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
I would like to have a working documentation with living links. Many links I click makes me end up in the labyrinth.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
If I search at e.g. [0], the first result at [1] can not be displayed because "This page does not exist yet". Actually during no search at all I could click at the link and get to the content. 
Sometimes I google something (e.g. [2,3]) and when I click at the link there are no entries either.
If required I can check for more examples. But instead of reading the documentation I started to read the code as it is more time-efficient and this is no good choice in general.

[0] http://docs.cherrypy.org/en/latest/search.html?q=error&check_keywords=yes&area=default
[1] http://docs.cherrypy.org/en/latest/pkg/cherrypy.tutorial.rst.html?highlight=error#module-cherrypy.tutorial.tut10_http_errors
[2] http://cherrypy.org/wiki/ErrorsAndExceptions#AnticipatedHTTPresponses
[3] http://docs.cherrypy.org/stable/

* **What is the expected behavior?**
I would like to see real documentation articles.

**Comment by webknjaz** [comment] 2017-04-04 19:35
Hello,

As for [0]/[1] it's a duplicate of #1571. So I'm going to close this one.

Also, cherrypy.org/wiki [2] is no longer supported. There was some deprecated information about outdated versions of CherryPy.

Regarding [3] I have no idea how that got into google.. Anyway RTD isn't configured to support such scheme anymore.

**Closed as completed by webknjaz** 2017-04-04 19:35 UTC
Labels: bug, duplicate
