### ISSUE TITLE
Error: TypeError: staticfile() got multiple values for keyword argument 'filename'

### ISSUE THREAD

**Issue by time-river** [cherrypy/cherrypy#1623] opened 2017-08-17 10:32 UTC
* **I'm submitting a ...**
bug report

* **What is the current behavior?**
```log
[17/Aug/2017:18:17:13] HTTP 
Request Headers:
  REFERER: https://147.2.212.144:8001/plugins/kimchi/novnc/vnc_auto.html?port=8001&path=/websockify?token=Vk5D&encrypt=1
  HOST: 147.2.212.144
  CONNECTION: close
  Remote-Addr: 127.0.0.1
  X-REAL-IP: 147.2.212.73
  ACCEPT: image/webp,image/apng,image/*,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
  COOKIE: wokLang=en_US; username=river; user_role=admin; lastPage="/#plugins/kimchi/tabs/guests"; wok=cf2a807d2d726db5ce3b86822dea991cebdb3234; token=Vk5D
  ACCEPT-LANGUAGE: zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4,zh-TW;q=0.2
  X-FORWARDED-FOR: 147.2.212.73
  DNT: 1
  ACCEPT-ENCODING: gzip, deflate, br
INFO:cherrypy.error.140087717154000:[17/Aug/2017:18:17:13] HTTP 
Request Headers:
  REFERER: https://147.2.212.144:8001/plugins/kimchi/novnc/vnc_auto.html?port=8001&path=/websockify?token=Vk5D&encrypt=1
  HOST: 147.2.212.144
  CONNECTION: close
  Remote-Addr: 127.0.0.1
  X-REAL-IP: 147.2.212.73
  ACCEPT: image/webp,image/apng,image/*,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
  COOKIE: wokLang=en_US; username=river; user_role=admin; lastPage="/#plugins/kimchi/tabs/guests"; wok=cf2a807d2d726db5ce3b86822dea991cebdb3234; token=Vk5D
  ACCEPT-LANGUAGE: zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4,zh-TW;q=0.2
  X-FORWARDED-FOR: 147.2.212.73
  DNT: 1
  ACCEPT-ENCODING: gzip, deflate, br
[17/Aug/2017:18:17:13] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cptools.py", line 185, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for keyword argument 'filename'
ERROR:cherrypy.error.140087717154000:[17/Aug/2017:18:17:13] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cptools.py", line 185, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for keyword argument 'filename'
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.

I debug it, modify the code:
```python
# /usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cptools.py
        @expose
        def handle_func(*a, **kw):
            print("args: ", args)
            print("self._merged_args(kwargs): ", self._merged_args(kwargs))
            handled = self.callable(*args, **self._merged_args(kwargs))
            if not handled:
                raise cherrypy.NotFound()
            return cherrypy.serving.response.body
        return handle_func
```
print it:
```log
('args: ', ('/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/favicon.ico',))
('self._merged_args(kwargs): ', {'filename': '/usr/share/wok/ui/images/logo.ico'})
```

and found the `staticfile`:
```python
def staticfile(filename, root=None, match='', content_types=None, debug=False):
```
 
Here: 
Because of `args` is not `None` and `self._merged_args(kwargs)` has the key `filename`, 
the repeat incoming parameter `filename` results in the broken.

* **What is the expected behavior?**
:-)

* **What is the motivation / use case for changing the behavior?**
I could solve adding these code:
```python
--- cherrypy/_cptools.py	2017-08-17 12:38:22.738399515 +0800
+++ /usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cptools.py	2017-08-17 18:27:16.799323121 +0800
@@ -179,7 +179,12 @@
         """
         @expose
         def handle_func(*a, **kw):
-            handled = self.callable(*args, **self._merged_args(kwargs))
+            parameters = ('filename', 'root', 'match', 'content_types', 'debug')
+            kws = self._merged_args(kwargs)
+            for i in range(len(args)):
+                kws.pop(parameters[i], None) 
+            handled = self.callable(*args, **kws)
             if not handled:
                 raise cherrypy.NotFound()
             return cherrypy.serving.response.body
```
But I don't know what these would result to, and I don't know cherrypy's principle...
Let you help me.

* **Please tell us about your environment:**

- Python version: 2.7.13
- OS: openSUSE Tumbleweed
- Kimchi: 2.5.0
- Wok: 2.5.0

**Comment by webknjaz** [comment] 2017-08-17 21:30
Hello @time-river! Thank you for filing this issue.

Could you please describe sufficient steps to reproduce? I'm not really getting what app you are running and how.

Also, I'd recommend you sending us patches in a for of Pull Request, which would ease the review process dramatically. Thanks in advance :)

**Comment by time-river** [comment] 2017-08-18 04:58
setps:
1. `wokd --environment=dev`
2. click view console
3. find `TypeError: staticfile() got multiple values for keyword argument 'filename'` in output

attention:
`/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypyfavicon.ico`
`/usr/share/wok/ui/images/logo.ico`
Two pictures must exist.

Err, My patch has already pasted. The key is simultaneously with two identical parameters `filename` passed to `staticfile(filename, root=None, match='', content_types=None, debug=False)`.

The most important, parameter check should appear here.

And, is it the bug from Kimchi ?

**Comment by webknjaz** [comment] 2017-08-18 16:58
What is wokd? Please provide us pure CherryPy example? If you are going to demonstrate some problem, please don't include third-party dependencies. If you are having issues with third party apps, please seek support from their authors.

`staticfiles()` worked well for ages, so if there is some specific corner case, please demonstrate it with a minimum reproducible example.

**Comment by webknjaz** [comment] 2017-08-19 19:01
Currently this looks like a bug within software you are using, so I'm closing this issue. But if you'd come up with the evidence of bug in CherryPy, feel free to post it here and reopen this case.

**Closed as completed by webknjaz** 2017-08-19 19:01 UTC

**Comment by sanjaySP** [comment] 2018-08-13 08:12
###  I had the same issue.
i resolved it by _**removing**_ the fav icon path in the config and used the **static path** 
`/favicon.ico': {
                'tools.staticfile.on': True,
                'tools.staticfile.filename': '/static/ico/favicon.ico'
            }`
i added this in the html file.
`<link rel="shortcut icon" href="/static/img/user-avatar.png">` in the html file

This is caused due to the override of the ** default icon** of Cherrypy.
We have already exposed the **_static_** directory. so we can directly use it to override in the _ html file_.
