### ISSUE TITLE
18.7.0: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [cherrypy/cherrypy#1970] opened 2022-07-16 23:55 UTC
Looks like documentation build is broken
```console
[tkloczko@devel-g2v cherrypy-18.7.0]$ PYTHONPATH=$PWD /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.7.0/docs/conf.py", line 53, in <module>
    prj_py_min_supported, prj_py_max_supported = map(
ValueError: not enough values to unpack (expected 2, got 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.7.0/docs/conf.py", line 53, in <module>
    prj_py_min_supported, prj_py_max_supported = map(
ValueError: not enough values to unpack (expected 2, got 0)


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.7.0/docs/conf.py", line 53, in <module>
    prj_py_min_supported, prj_py_max_supported = map(
ValueError: not enough values to unpack (expected 2, got 0)

```

**Comment by jcfp** [comment] 2022-07-17 21:05
I was just about to report this as well. The cause seems to be `get_supported_pythons` in docs/conf.py returning an empty list now that PKG-INFO no longer lists any specific `Classifier: Programming Language :: Python :: 3.x` in 18.7.0 and newer.

**Comment by jaraco** [comment] 2023-12-13 14:38
That's interesting. I also observe that docs builds are failing recently (18.9.0 build failed in RTD). Curiously, the 18.8.0 release did build.

**Comment by webknjaz** [comment] 2023-12-13 15:44
@jaraco that happened when you merged the skeleton the previous time and I seem to recall fixing it shortly after that on the main. Those classifiers are used to display the range of tested versions in the docs. I implemented reading from the metadata years ago so there's no duplication anymore.

**Closed as completed** 2023-12-13 15:45 UTC
