### ISSUE TITLE
Re-spawning with frozen applications

### ISSUE THREAD

**Issue by Safihre** [cherrypy/cherrypy#1526] opened 2016-11-30 08:59 UTC
The changes to the re-spawning code work great for calling scripts, but have some side-effects when CherryPy get's frozen into an ```.exe``` where it calls the ```.exe``` as if it's the python interpreter using the parameters it was frozen with.
For example:
```2016-11-29 22:08:08,905::INFO::[_cplogging:219] [29/Nov/2016:22:08:08] ENGINE Re-spawning C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe -E -OO -S C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe```
Our current release uses CherryPy 6.0.2 which only included ```sys.argv```.

Simple solution: [check if it's a frozen app](https://pythonhosted.org/PyInstaller/runtime-information.html) and then don't include the interpreter flags.
```python
        try:
            args = self._get_true_argv()
        except NotImplementedError:
            """It's probably win32"""
            if getattr(sys, 'frozen', False):
                args = [sys.executable] + sys.argv
            else:
                args = [sys.executable] + _args_from_interpreter_flags() + sys.argv
```

I currently can't check how this would work on macOS when it gets frozen into an App. Since macOS does have the ```self._get_true_argv()``` I am not sure what will happen but I imagine a similar thing.

> 3. AFAIK these tools like py2exe never worked really well

They actually work quite well, we have 100.000+ happy users on Windows/macOS that don't have to bother with command line things and get our app with CherryPy setup with just a few clicks 😊

**Comment by jaraco** [comment] 2016-11-30 14:44
I believe this behavior is a regression stemming from #1504. @webknjaz should be able to implement a fix.

**Comment by webknjaz** [comment] 2016-11-30 18:20
@Safihre thanks for the investigation and the link you provided. I'll look into this later, meanwhile feel free to submit a PR.
If this fix is all we need I'd move it to the beginning of `_args_from_interpreter_flags()`:
```python
if getattr(sys, 'frozen', False):
    return ()
```

On the other hand, we need to check whether there's an option/need of surviving command line args.
Also I'll need your help with testing this against other OSes. TIA.

**Comment by Safihre** [comment] 2016-12-01 07:20
Our OSX guy will test it soon, I only do the Windows stuff. Will let you know!

**Comment by webknjaz** [comment] 2016-12-01 10:14
@Safihre What is the full command for running your executable? What is in `sys.executable` and `sys.argv` when running in frozen mode?

**Comment by webknjaz** [comment] 2016-12-01 10:15
P.S. AFAIK `self._get_true_argv()` is available only under GNU/Linux.

**Comment by Safihre** [comment] 2016-12-01 10:32
> What is in sys.executable and sys.argv when running in frozen mode?

```sys.executable = C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe```
```sys.args = C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe <whatever the user put when starting the exe>``` 

> P.S. AFAIK self._get_true_argv() is available only under GNU/Linux.

Also on macOS, just tested it by modifying the code:
```python
args = self._get_true_argv()
print str(args)
['python', '-OO', 'SABnzbd.py']
```
I see, however, that for the macOS frozen app we have our own restart code (made long ago) with comment:
```# When executing from sources on osx, after a restart, process is detached from console. If OSX frozen restart of app instead of embedded python```

**Comment by webknjaz** [comment] 2016-12-01 12:52
That sounds interesting. So with the patch it would be restarted with
```python
os.execv(
    'C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe',
    ['C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe',
     'C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe']
)
```
Weird ;)

Could you please check for CherryPy v6.0.2 whether the `os.execv()` arguments built are the same?

**Comment by webknjaz** [comment] 2016-12-01 13:10
@Safihre do you have any ideas of how can we implement automatic testing of re-spawning in frozen mode? What it takes to compile an app with py2exe tool?

**Comment by Safihre** [comment] 2016-12-01 13:22
Indeed you are right, I just recompiled with a print-statement for and for ```sys.executable``` and ```args``` given to ```os.execv()``` are:

8.1.2 (unpatched)
```python
'E:\sabsupport\builder\src\dist\SABnzbd-console.exe'
['"E:\\sabsupport\\builder\\src\\dist\\SABnzbd-console.exe"', '"-E"', '"-OO"', '"-S"', '"E:\\sabsupport\\builder\\src\\dist\\SABnzbd-console.exe"']
```
6.0.2
```python
'E:\sabsupport\builder\src\dist\SABnzbd-console.exe'
['"E:\\sabsupport\\builder\\src\\dist\\SABnzbd-console.exe"', '"E:\\sabsupport\\builder\\src\\dist\\SABnzbd-console.exe"']
```

**Comment by Safihre** [comment] 2016-12-01 15:12
Compiling with py2exe is not too fast and does lots of side-tasks to make a working EXE. Might be a bit overkill.

**Comment by webknjaz** [comment] 2016-12-01 15:19
@Safihre could you please re-test your app with current master (and commit I pushed).
P.S. Why don't you add cherrypy as a submodule to your project instead of copy-pasting it every time?

**Comment by Safihre** [comment] 2016-12-01 16:04
You made small error, ```hasattr``` takes only 2 arguments and can't do ```+``` on a list and a tuple.

Since a frozen app doesn't need the extra ```sys.executable``` how about something like this? (snipped)
Tested and works for Python and frozen :blush:

```python
    def _do_execv(self):
        ...
        except NotImplementedError:
            """It's probably win32 or GAE"""
            args = self._get_interpreter_argv() + sys.argv
        ...

    @staticmethod
    def _get_interpreter_argv():
        ...
        return ([]
                if hasattr(sys, 'frozen')
                else [sys.executable] + _args_from_interpreter_flags())
```

We didn't do submodule so we can quickly make alterations for bugs our users were experiencing. 
For 6.0.2 there were quite a few, but with 8.1.2 it's really only #1509 👍👍

**Comment by webknjaz** [comment] 2016-12-01 16:26
I don't agree with moving `sys.executable` part to `_get_interpreter_argv()` method, since it isn't related to the function purpose. Go ahead and test it fixed :)

**Comment by webknjaz** [comment] 2016-12-01 22:58
@Safihre I'm marking this as closed, feel free to re-open this issue or file a new one if needed.

**Closed as completed by webknjaz** 2016-12-01 22:58 UTC
Labels: bug
