### ISSUE TITLE
Log is redirecting to console even when cherrypy.log.screen is False

### ISSUE THREAD

**Issue by ramonmedeiros** [cherrypy/cherrypy#1566] opened 2017-02-20 20:38 UTC
Running cherrypy server on Kimchi-Project, i got a stranger behaviour while changing logging options.

* **I'm submitting a ...**
[x] bug report

* **What is the current behavior?**
When running cherrypy, even setting cherrpy.log.screen = False, or updating cherrypy.config for it, the server still sends log to console

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
Run server wtih console = False and watch. You can try it at my project:

https://github.com/kimchi-project/wok/

* **What is the expected behavior?**
Starting server only logging files, not screen

* **What is the motivation / use case for changing the behavior?**
Avoid log on screen

* **Please tell us about your environment:**

- Python version: 3.6.X
Fedora 25 x86_64
Chrome

**Comment by webknjaz** [comment] 2017-02-21 13:17
Hi @ramonmedeiros,

Are you running the app in daemon mode?

Could you please provide the smallest reproducible example of an app?

**Comment by ramonmedeiros** [comment] 2017-02-21 16:26
Yep. I will put some references from the code

https://github.com/kimchi-project/wok/blob/master/src/wok/server.py

**Comment by ramonmedeiros** [comment] 2017-02-28 18:36
HI @webknjaz, the server is described in the above file and run from this script 
https://github.com/kimchi-project/wok/blob/master/src/wokd.in

**Comment by webknjaz** [comment] 2017-03-01 10:31
There's too many lines in it. I guess the minimum reproducible code snippet could be just a few lines. Now as it looks too puzzling/time consuming for me to dig into project this big.

**Comment by ramonmedeiros** [comment] 2017-03-02 15:44
I will try to highlight some parts:

src/wok/server.py
```

        cherrypy.engine.timeout_monitor.unsubscribe()
        cherrypy.tools.nocache = cherrypy.Tool('on_end_resource', set_no_cache)
        cherrypy.tools.wokauth = cherrypy.Tool('before_handler', auth.wokauth)

        # Setting host to 127.0.0.1. This makes wok run
        # as a localhost app, inaccessible to the outside
        # directly. You must go through the proxy.
        cherrypy.server.socket_host = '127.0.0.1'
        cherrypy.server.socket_port = options.cherrypy_port

        max_body_size_in_bytes = eval(options.max_body_size) * 1024
        cherrypy.server.max_request_body_size = max_body_size_in_bytes

        cherrypy.log.access_file = options.access_log
        cherrypy.log.error_file = options.error_log

        logLevel = LOGGING_LEVEL.get(options.log_level, logging.INFO)
        dev_env = options.environment != 'production'

        # Enable cherrypy screen logging if running environment
        # is not 'production'
        if dev_env:
            cherrypy.log.screen = True

        # close standard file handlers because we are going to use a
        # watchedfiled handler, otherwise we will have two file handlers
        # pointing to the same file, duplicating log enries
        for handler in cherrypy.log.access_log.handlers[:]:
            if isinstance(handler, logging.FileHandler):
                cherrypy.log.access_log.removeHandler(handler)

        for handler in cherrypy.log.error_log.handlers[:]:
            if isinstance(handler, logging.FileHandler):
                cherrypy.log.error_log.removeHandler(handler)

        # set logLevel
        cherrypy.log.access_log.setLevel(logLevel)
        cherrypy.log.error_log.setLevel(logLevel)

        # Create handler to access log file
        h = logging.handlers.WatchedFileHandler(options.access_log, 'a',
                                                delay=1)
        h.setLevel(logLevel)
        h.setFormatter(cherrypy._cplogging.logfmt)

        # Add access log file to cherrypy configuration
        cherrypy.log.access_log.addHandler(h)

        # Create handler to error log file
        h = SafeWatchedFileHandler(options.error_log, 'a', delay=1)
        h.setLevel(logLevel)
        h.setFormatter(cherrypy._cplogging.logfmt)

        # Add error log file to cherrypy configuration
        cherrypy.log.error_log.addHandler(h)

        # start request logger
        self.reqLogger = RequestLogger()

        # Handling running mode
        if not dev_env:
            cherrypy.config.update({'environment': 'production'})

        for ident, node in sub_nodes.items():
            if node.url_auth:
                cfg = self.configObj
                ident = "/%s" % ident
                cfg[ident] = {'tools.wokauth.on': True}

        cherrypy.tree.mount(WokRoot(model.Model(), dev_env),
                            options.server_root, self.configObj)

        cherrypy.lib.sessions.init()

```

Start server
```
    def start(self):
        # Subscribe to SignalHandler plugin
        if hasattr(cherrypy.engine, 'signal_handler'):
            cherrypy.engine.signal_handler.subscribe()

        cherrypy.engine.start()

```

**Comment by webknjaz** [comment] 2017-03-02 18:18
Could you please remove **all** unrelated parts from your snippets?

**Comment by ramonmedeiros** [comment] 2017-03-03 13:23
I will try. Not sure which part is relevant for your debug:

src/wok/server.py
```

        cherrypy.engine.timeout_monitor.unsubscribe()
        cherrypy.tools.nocache = cherrypy.Tool('on_end_resource', set_no_cache)
        cherrypy.tools.wokauth = cherrypy.Tool('before_handler', auth.wokauth)


        max_body_size_in_bytes = eval(options.max_body_size) * 1024
        cherrypy.server.max_request_body_size = max_body_size_in_bytes

        # Handling running mode
        if not dev_env:
            cherrypy.config.update({'environment': 'production'})


        cherrypy.tree.mount(WokRoot(model.Model(), dev_env),
                            options.server_root, self.configObj)

        cherrypy.lib.sessions.init()

```

Start server
```
    def start(self):
        # Subscribe to SignalHandler plugin
        if hasattr(cherrypy.engine, 'signal_handler'):
            cherrypy.engine.signal_handler.subscribe()

        cherrypy.engine.start()

```

**Comment by webknjaz** [comment] 2017-03-03 17:13
There's no tools like nocache or wokauth in cherrypy as well as no WokRoot, nor dev_env.
I won't be able to run this by copy-pasting that into an empty module.

**Comment by ramonmedeiros** [comment] 2017-03-03 20:36
Hi @webknjaz, i'm not a expert with cherrypy. What you me to show about this?

**Comment by webknjaz** [comment] 2017-03-09 09:19
@ramonmedeiros I just need a simple app, which doesn't include anything from your project (which I won't be running) and includes a config and demo of what you are referring to w/ logging.

**Comment by sandipb** [comment] 2017-04-25 10:36
@webknjaz how about this?

```python
import cherrypy
import os
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s.%(msecs)03d [%(levelname)s] (%(name)s) %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
cherrypy.config.update({
            'environment': 'production',
            'server.socket_port': 2400,
            'log.screen': False,
            'log.access_file': os.path.join(os.getcwd(), 'access.log'),
            'log.error_file': os.path.join(os.getcwd(), 'error.log')
})

class RestAPIApp(object):

    @cherrypy.expose
    def admin(self):
        return "GOOD\r\n"

cherrypy.quickstart(RestAPIApp(), script_name='', config=None)
```

On executing:

```console
$ python cherry_bug.py
2017-04-25 03:32:23.747 [INFO] (cherrypy.error) [25/Apr/2017:03:32:23] ENGINE Listening for SIGHUP.
2017-04-25 03:32:23.748 [INFO] (cherrypy.error) [25/Apr/2017:03:32:23] ENGINE Listening for SIGTERM.
2017-04-25 03:32:23.748 [INFO] (cherrypy.error) [25/Apr/2017:03:32:23] ENGINE Listening for SIGUSR1.
2017-04-25 03:32:23.748 [INFO] (cherrypy.error) [25/Apr/2017:03:32:23] ENGINE Bus STARTING
2017-04-25 03:32:23.748 [INFO] (cherrypy.error) [25/Apr/2017:03:32:23] ENGINE Started monitor thread '_TimeoutMonitor'.
2017-04-25 03:32:23.860 [INFO] (cherrypy.error) [25/Apr/2017:03:32:23] ENGINE Serving on http://127.0.0.1:2400
2017-04-25 03:32:23.860 [INFO] (cherrypy.error) [25/Apr/2017:03:32:23] ENGINE Bus STARTED
^C2017-04-25 03:32:27.498 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE Keyboard Interrupt: shutting down bus
2017-04-25 03:32:27.498 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE Bus STOPPING
2017-04-25 03:32:27.501 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 2400)) shut down
2017-04-25 03:32:27.501 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE Stopped thread '_TimeoutMonitor'.
2017-04-25 03:32:27.501 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE Bus STOPPED
2017-04-25 03:32:27.502 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE Bus EXITING
2017-04-25 03:32:27.502 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE Bus EXITED
2017-04-25 03:32:27.502 [INFO] (cherrypy.error) [25/Apr/2017:03:32:27] ENGINE Waiting for child threads to terminate...
```
What I have noticed is if in the main app, we configure the root logger in some way, this behavior of logging to screen happens. If I don't do `logging.basicConfig` then the log is not shown on screen.

**Comment by sandipb** [comment] 2017-04-25 10:52
There seems to be an easy solution to this. Just set `logging.getLogger("cherrypy").propagate = False` at the top of the file to never see cherrypy logs on screen.

```python
import cherrypy
import os
import logging

logging.getLogger("cherrypy").propagate = False

logging.basicConfig(level=logging.INFO, format="%(asctime)s.%(msecs)03d [%(levelname)s] (%(name)s) %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
cherrypy.config.update({
            'environment': 'production',
            'server.socket_port': 2400,
            'log.screen': False,
            'log.access_file': os.path.join(os.getcwd(), 'access.log'),
            'log.error_file': os.path.join(os.getcwd(), 'error.log')
})

class RestAPIApp(object):

    @cherrypy.expose
    def admin(self):
        return "GOOD\r\n"

logging.info("Starting cherrypy")
cherrypy.quickstart(RestAPIApp(), script_name='', config=None)
logging.info("Stopped cherrypy")
```
Output.
```console
$ python cherry_bug.py
2017-04-25 03:49:15.729 [INFO] (root) Starting cherrypy
2017-04-25 03:49:18.842 [INFO] (root) Stopped cherrypy
$
```

**Comment by webknjaz** [comment] 2017-04-25 13:02
Good catch @sandipb :)
It's expected that if you actually affect cherrypy's logger its behavior may change.

I'm going to close current issue. But should you have any questions — feel free to ask.

**Comment by sandipb** [comment] 2017-04-25 19:33
Actually in this case, cherrypy's logger is not changed by the user - the root logger is.

The problem that is happening is that while cherrypy has its own handlers, it propagates its log messages to the root logger. And anyone who attaches a handler to the root logger is going to see this problem.

While I suggested a workaround (disabling upward propagation of the cherrypy logger), could it be set to be the default behavior?

That is - can cherrypy code be changed to disable propagation in the `cherrypy` logger? Is there any  use case for allowing logs to "leak" to the root handler that I cannot think of right now?

**Comment by webknjaz** [comment] 2017-04-25 20:31
@sandipb sounds reasonable. I think there's no use case for such leaking. Feel free to craft a PR to change this. I'm okay with merging such change.

**Comment by webknjaz** [comment] 2017-08-19 19:22
It turned out that logging propagation is covered in docs:
* http://docs.cherrypy.org/en/latest/basics.html#play-along-with-your-other-loggers
* http://docs.cherrypy.org/en/latest/deploy.html#tornado

I don't think we should change defaults, since is is better to have default logging to dev mode.

@jaraco what do you think about this?

P.S. Closing for now.

**Closed as completed by webknjaz** 2017-08-19 19:22 UTC
